pipeline {
    agent any 
    stages {
        stage('Static Analysis') {
            steps {
                echo 'hey mukesh here' 
            }
        }
        stage('Compile') {
            steps {
                echo 'we are Compiling the source code' 
            }
        }
        stage('Security Check') {
            steps {
                echo 'wooh security checking' 
            }
        }
        stage('Run Unit Tests') {
            steps {
                echo 'run the test man' 
            }
        }
        stage('Run Integration Tests') {
            steps {
                echo 'Run only crucial integration tests from the source code' 
            }
        }
        stage('Publish Artifacts') {
            steps {
                echo 'save it man' 
            }
        }
    }
}
